#!/bin/bash

# -----------------------------------------------------------------------------
# input for jibri-jibri-installer
# -----------------------------------------------------------------------------
# core
out <<< "checking the number of cores..."
CORES=$(nproc --all)
if [[ "$CORES" -lt 4 ]]; then
    out <<EOF
Aborted! Not enough cores: $CORES
Recommendation: It should be at least 4 cores
EOF
    exit 1
fi

# snd_aloop
out <<< "checking the snd-aloop support..."

[[ "$DISTRO" = "focal" ]] && \
    apt-get $APT_PROXY_OPTION -y install linux-modules-extra-$(uname -r) \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" || \
    true

[[ "$DISTRO" = "buster" ]] && \
    KERNEL="linux-image-$(dpkg --print-architecture)" || \
    KERNEL="linux-image-generic"

modprobe snd_aloop 2>/dev/null || true
if [[ -z "$(grep snd_aloop /proc/modules)" ]]; then
    out <<EOF
Aborted! This kernel ($(uname -r)) does not support snd_aloop module.
Recommendation: Install the standard Linux kernel package and reboot with it.
                Probably it's the "$KERNEL" package in your case.
EOF
    exit 1
fi
