#!/bin/bash
set -e

# -----------------------------------------------------------------------------
# globals
# -----------------------------------------------------------------------------
JITSI_HOST=$JITSI_HOST

DEBIAN_FRONTEND=noninteractive
APT_PROXY_OPTION=$APT_PROXY_OPTION

PROSODY_PLUGINS=https://raw.githubusercontent.com/jitsi-contrib/prosody-plugins/main
JITSI_TMPL=https://raw.githubusercontent.com/jitsi-contrib/installers/main/templates/jitsi

JITSI_MEET_CONFIG=/etc/jitsi/meet/$JITSI_HOST-config.js
PROSODY_CONFIG=/etc/prosody/conf.avail/$JITSI_HOST.cfg.lua
NGINX_CONFIG=/etc/nginx/sites-available/$JITSI_HOST.conf

CHECKMYPORT=https://checkmyport.emrah.com
TCP=(80 443 4444 5222 5280 5269 5347 5349 8080 8888 9090)
UDP=(5000 5349 10000)


# -----------------------------------------------------------------------------
# globals (extra)
# -----------------------------------------------------------------------------
JIBRI_TMPL=https://raw.githubusercontent.com/jitsi-contrib/installers/main/templates/jibri
APP_ID="jitsi-$RANDOM"
APP_SECRET="$(openssl rand -hex 20)"
PJPROJECT_REPO=https://github.com/jitsi/pjproject
PJPROJECT_BRANCH="jibri-2.10-dev1"


# -----------------------------------------------------------------------------
# output format
# -----------------------------------------------------------------------------
out() {
    printf "\n"

    while IFS= read -r line; do
        printf "\033[0;31m>>>\033[0m \033[0;33m%s\033[0m\n" "$line"
    done
}


# -----------------------------------------------------------------------------
# trap on exit
# -----------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        out <<< "Something went wrong. Not completed!"
        exit 1
    else
        out <<EOF
Installation Duration: $DURATION
Completed successfully!
EOF
        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT


# -----------------------------------------------------------------------------
# environment
# -----------------------------------------------------------------------------
START_TIME=$(date +%s)
BASEDIR=$(pwd)
DEFAULT_ROUTE=$(ip route | egrep '^default ' | head -n1)
PUBLIC_INTERFACE=${DEFAULT_ROUTE##*dev }
PUBLIC_INTERFACE=${PUBLIC_INTERFACE/% */}
PUBLIC_IP=$(ip addr show $PUBLIC_INTERFACE | egrep "$PUBLIC_INTERFACE$" | \
            xargs | cut -d " " -f 2 | cut -d "/" -f1)


# -----------------------------------------------------------------------------
# input check
# -----------------------------------------------------------------------------
clear

# are you sure
out <<EOF
This script can be harmful and will remove already installed Jitsi if exists.
Don't use it on a working production server.
Write YES (uppercase) and press enter if you are crazy!
EOF

read answer
if [[ "$answer" != "YES" ]]; then
    out <<EOF
Aborted! not approved, typed: $answer
Recommendation: Use this script on a newly installed machine
EOF
    exit 1
fi


# whoami
out <<< "checking the user account..."
if [[ "$(whoami)" != "root" ]]; then
    out <<EOF
Aborted! Your are not the root user: $(whoami)
Recommendation: Use the following command to be the 'root' user

    su -l
EOF
    exit 1
fi

# distro
out <<< "checking the distro..."
[[ $(command -v lsb_release) ]] && \
    DISTRO=$(lsb_release -c | cut -d: -f2 | xargs) || \
    DISTRO=$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)

if [[ "$DISTRO" != "focal" ]] && \
   [[ "$DISTRO" != "bullseye" ]] && \
   [[ "$DISTRO" != "buster" ]]; then
    out <<EOF
Aborted! Your distro is not supported
Recommendation: Switch to Debian 11 Bullseye or Ubuntu 20.04 Focal Fossa
EOF
    exit 1
fi

# memory
out <<< "checking the total memory..."
MEM=$(cat /proc/meminfo | grep MemTotal | egrep -o "[0-9]*")
if [[ "$MEM" -lt 7800000 ]]; then
    out <<EOF
Aborted! Not enough memory: $MEM kB
Recommendation: The total memory should be at least 8 GB
EOF
    exit 1
fi

# jitsi host address
out <<< "checking Jitsi FQDN..."
if [[ -z "$JITSI_HOST" ]]; then
    out <<EOF
Aborted! Unknown Jitsi host address
Recommendation: Set Jitsi host address according to the following command
  and try again

    export JITSI_HOST=jitsi.yourdomain.com
EOF
    exit 1
fi

# jitsi fqdn
if [[ -z "$(echo $JITSI_HOST | egrep -o '[a-zA-Z]')" ]]; then
    out <<EOF
Aborted! Jitsi host address is not FQDN: $JITSI_HOST
Recommendation: Don't use an IP address, use a valid FQDN address
EOF
    exit 1
fi

# turn host address
out <<< "checking TURN FQDN..."
if [[ -z "$TURN_HOST" ]]; then
    out <<EOF
Aborted! Unknown TURN host address
Recommendation: Set TURN host address according to the following command
  and try again

    export TURN_HOST=turn.yourdomain.com
EOF
    exit 1
fi

# turn fqdn
if [[ -z "$(echo $TURN_HOST | egrep -o '[a-zA-Z]')" ]]; then
    out <<EOF
Aborted! TURN host address is not FQDN: $TURN_HOST
Recommendation: Don't use an IP address, use a valid FQDN address
EOF
    exit 1
fi

# jitsi == turn
if [[ "$JITSI_HOST" = "$TURN_HOST" ]]; then
    out <<EOF
Aborted! Jitsi host address and TURN host address are the same
Recommendation: Use different addresses for Jitsi and TURN

    export JITSI_HOST=jitsi.yourdomain.com
    export TURN_HOST=turn.yourdomain.com
EOF
    exit 1
fi


# -----------------------------------------------------------------------------
# input check (extra)
# -----------------------------------------------------------------------------
# core
out <<< "checking the number of cores..."
CORES=$(nproc --all)
if [[ "$CORES" -lt 4 ]]; then
    out <<EOF
Aborted! Not enough cores: $CORES
Recommendation: It should be at least 4 cores
EOF
    exit 1
fi

# snd_aloop
out <<< "checking the snd-aloop support..."

if [[ "$DISTRO" = "focal" ]]; then
    apt-get $APT_PROXY_OPTION -y install linux-modules-extra-$(uname -r) \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold"
fi

if [[ "$DISTRO" = "bullseye" ]] || \
   [[ "$DISTRO" = "buster" ]]; then
    KERNEL="linux-image-$(dpkg --print-architecture)"
else
    KERNEL="linux-image-generic"
fi

modprobe snd_aloop 2>/dev/null || true
if [[ -z "$(grep snd_aloop /proc/modules)" ]]; then
    out <<EOF
Aborted! This kernel ($(uname -r)) does not support snd_aloop module.
Recommendation: Install the standard Linux kernel package and reboot with it.
                Probably it's the "$KERNEL" package in your case.
EOF
    exit 1
fi


# -----------------------------------------------------------------------------
# remove the old installation if exists
# -----------------------------------------------------------------------------
out <<< "removing the old installation if exists..."

systemctl stop sip-xorg.service || true
systemctl stop jibri-xorg.service || true
systemctl stop jigasi.service || true
systemctl stop jitsi-videobridge2.service || true
systemctl stop jicofo.service || true
systemctl stop prosody.service || true
systemctl stop coturn.service || true
systemctl stop stunnel4.service || true
systemctl stop nginx.service || true

apt-get -y purge jibri || true
apt-get -y purge jigasi || true
apt-get -y purge 'jitsi-*' || true
apt-get -y purge jicofo || true
apt-get -y purge prosody || true
apt-get -y purge 'prosody-*' || true
apt-get -y purge coturn || true
apt-get -y purge stunnel || true
apt-get -y purge nginx || true
apt-get -y purge 'nginx-*' || true
apt-get -y purge 'openjdk-*' || true
apt-get -y purge 'adoptopenjdk-*' || true
apt-get -y purge chromium chromium-common chromium-driver || true
apt-get -y purge chromium-browser chromium-chromedriver || true
apt-get -y purge chromium-codecs-ffmpeg chromium-codecs-ffmpeg-extra || true
apt-get -y purge google-chrome-stable || true
apt-get -y purge ungoogled-chromium || true
apt-get -y purge va-driver-all vdpau-driver-all || true
apt-get -y autoremove --purge

deluser jibri || true
delgroup jibri || true

rm -rf /home/jibri
rm -rf /etc/chromium
rm -rf /etc/jitsi
rm -rf /etc/prosody
rm -rf /etc/nginx
rm -rf /etc/opt/chrome
rm -rf /usr/share/jitsi-meet
rm -rf /usr/share/jitsi-videobridge
rm -rf /usr/share/jicofo
rm -f  /etc/apt/sources.list.d/stretch.list
rm -f  /etc/apt/sources.list.d/buster.list
rm -f  /etc/apt/sources.list.d/jitsi-stable.list
rm -f  /etc/apt/sources.list.d/google-chrome.list
rm -f  /etc/apt/sources.list.d/ungoogled-chromium.list
rm -f  /usr/local/bin/chromedriver


# -----------------------------------------------------------------------------
# packages (base)
# -----------------------------------------------------------------------------
out <<< "installing base packages..."

for i in $(seq 3); do
    apt-get -y --allow-releaseinfo-change update && sleep 3 && break
done

apt-get $APT_PROXY_OPTION -y install apt-utils \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"
apt-get $APT_PROXY_OPTION -y upgrade \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"
apt-get $APT_PROXY_OPTION -y install wget curl ca-certificates openssl
apt-get $APT_PROXY_OPTION -y install apt-transport-https gnupg
apt-get $APT_PROXY_OPTION -y install iputils-ping dnsutils
apt-get $APT_PROXY_OPTION -y install tmux vim less ack jq rsync bzip2
apt-get $APT_PROXY_OPTION -y install procps htop bmon
apt-get $APT_PROXY_OPTION -y install net-tools ngrep ncat
apt-get $APT_PROXY_OPTION -y install ssl-cert certbot
apt-get $APT_PROXY_OPTION -y install gcc git


# -----------------------------------------------------------------------------
# environment check
# -----------------------------------------------------------------------------
# external ip
out <<< "checking the external IP..."
EXTERNAL_IP=$(dig -4 +short myip.opendns.com a @resolver1.opendns.com) || true
if [[ -z "$EXTERNAL_IP" ]]; then
    out <<EOF
Aborted! The external IP not found
Recommendation: Check if myip.opendns.com is accessible
EOF
    exit 1
fi

# jitsi host A record
out <<< "checking DNS record for $JITSI_HOST..."
IP=$(dig -4 +short $JITSI_HOST @resolver1.opendns.com | tail -1) || true
if [[ -z "$IP" ]]; then
    out <<EOF
Aborted! $JITSI_HOST is not resolvable on Internet
Recommendation: Set DNS A record for $JITSI_HOST on a public DNS
EOF
    exit 1
fi

# jitsi ip == external ip
out <<< "checking $JITSI_HOST resolved IP..."
if [[ "$IP" != "$EXTERNAL_IP" ]]; then
    out <<EOF
Aborted! $JITSI_HOST does not point to this server: $EXTERNAL_IP <> $IP
Recommendation: Set $EXTERNAL_IP as $JITSI_HOST A record
EOF
    exit 1
fi

# turn host A record
out <<< "checking DNS record for $TURN_HOST..."
IP=$(dig -4 +short $TURN_HOST @resolver1.opendns.com | tail -1) || true
if [[ -z "$IP" ]]; then
    out <<EOF
Aborted! $TURN_HOST is not resolvable on Internet
Recommendation: Set DNS CNAME or A record for $TURN_HOST on a public DNS
EOF
    exit 1
fi

# turn ip == external ip
out <<< "checking $TURN_HOST resolved IP..."
if [[ "$IP" != "$EXTERNAL_IP" ]]; then
    out <<EOF
Aborted! $TURN_HOST does not point to this server: $EXTERNAL_IP <> $IP
Recommendation: Set $EXTERNAL_IP as $TURN_HOST A record
EOF
    exit 1
fi


# -----------------------------------------------------------------------------
# port availability check
# -----------------------------------------------------------------------------
out <<< "checking the availability of TCP ports..."
netstat -ltnp | egrep '^tcp' | while read -r l; do
    port=$(echo $l | awk '{print $4}' | rev | cut -d: -f1 | rev)
    for p in ${TCP[*]}; do
        if [[ "$p" = "$port" ]]; then
            prog=$(echo $l | cut -d/ -f2)
            proto=$(echo $l | awk '{print $1}')
            out <<EOF
Aborted! The port $proto/$port is already in use by $prog
Recommendation: disable this application or change its port
EOF
            exit 1
        fi
    done
done

out <<< "checking the availability of UDP ports..."
netstat -lunp | egrep '^udp' | while read -r l; do
    port=$(echo $l | awk '{print $4}' | rev | cut -d: -f1 | rev)
    for p in ${UDP[*]}; do
        if [[ "$p" = "$port" ]]; then
            prog=$(echo $l | cut -d/ -f2)
            proto=$(echo $l | awk '{print $1}')
            out <<EOF
Aborted! The port $proto/$port is already in use by $prog
Recommendation: remove this application or change its port
EOF
            exit 1
        fi
    done
done


# -----------------------------------------------------------------------------
# accessibility check
# -----------------------------------------------------------------------------
TEXT=$(openssl rand -hex 20)

out <<< "checking the checkmyport service..."
RES=$(timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=$TEXT" || true)
if [[ "$RES" != "ok" ]]; then
    out <<EOF
Aborted! The accessibility check failed
Recommendation: Check if $CHECKMYPORT is accessible
EOF
    exit 1
fi

# tcp/80
out <<< "checking TCP/80 accessibility..."
(sleep 3 && \
    timeout 8 curl -s "$CHECKMYPORT?proto=tcp&port=80&text=$TEXT" \
    >/dev/null 2>&1 || true) &
RES=$(timeout 8 ncat -l 0.0.0.0 80 | tr -d '\0' || true)
if [[ "$RES" != "$TEXT" ]]; then
    out <<EOF
Aborted! TCP/80 is not accessible
Recommendation: Check firewall and NAT rules, allow TCP/80
EOF
    exit 1
fi

# tcp/443
out <<< "checking TCP/443 accessibility..."
(sleep 3 && \
    timeout 8 curl -s "$CHECKMYPORT?proto=tcp&port=443&text=$TEXT" \
    >/dev/null 2>&1 || true) &
RES=$(timeout 8 ncat -l 0.0.0.0 443 | tr -d '\0' || true)
if [[ "$RES" != "$TEXT" ]]; then
    out <<EOF
Aborted! TCP/443 is not accessible
Recommendation: Check firewall and NAT rules, allow TCP/443
EOF
    exit 1
fi

# udp/10000
out <<< "checking UDP/10000 accessibility..."
(sleep 3 && \
    timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=10000&text=$TEXT" \
    >/dev/null 2>&1 || true) &
RES=$(timeout 8 ncat -u -l 0.0.0.0 10000 | tr -d '\0' || true)
if [[ "$RES" != "$TEXT" ]]; then
    out <<EOF
Aborted! UDP/10000 is not accessible
Recommendation: Check firewall and NAT rules, allow UDP/10000
EOF
    exit 1
fi

# ports are ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-port" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# packages
# -----------------------------------------------------------------------------
# openjdk-11-jre-headless
apt-get $APT_PROXY_OPTION -y install openjdk-11-jre-headless

# jitsi-meet
out <<< "installing Jitsi..."

wget -T 10 -qO /tmp/jitsi.gpg.key https://download.jitsi.org/jitsi-key.gpg.key
cat /tmp/jitsi.gpg.key | gpg --dearmor > /usr/share/keyrings/jitsi.gpg
wget -T 10 -O /etc/apt/sources.list.d/jitsi-stable.list \
    $JITSI_TMPL/etc/apt/sources.list.d/jitsi-stable.list

apt-get update
debconf-set-selections <<< \
    "jicofo jitsi-videobridge/jvb-hostname string $JITSI_HOST"
debconf-set-selections <<< \
    "jitsi-meet-web-config jitsi-meet/cert-choice select Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)"
apt-get $APT_PROXY_OPTION -y --install-recommends install jitsi-meet
apt-get $APT_PROXY_OPTION -y install libnginx-mod-http-lua
apt-get $APT_PROXY_OPTION -y install luarocks liblua5.2-dev

# packages are ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-package" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# packages (extra, token)
# -----------------------------------------------------------------------------
out <<< "installing token packages..."

debconf-set-selections <<< \
    "jitsi-meet-tokens jitsi-meet-tokens/appid string $APP_ID"
debconf-set-selections <<< \
    "jitsi-meet-tokens jitsi-meet-tokens/appsecret password $APP_SECRET"
apt-get -y install jitsi-meet-tokens

# token packages are ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-package-token" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# packages (extra, jibri)
# -----------------------------------------------------------------------------
out <<< "installing jibri packages..."

if [[ "$DISTRO" = "bullseye" ]]; then
    sed -i "s~ bullseye main$~ bullseye main contrib non-free~" \
        /etc/apt/sources.list
    sed -i "s~ bullseye-updates main$~ bullseye-updates main contrib non-free~" \
        /etc/apt/sources.list
    sed -i "s~ bullseye-security main$~ bullseye-security main contrib non-free~" \
        /etc/apt/sources.list
elif [[ "$DISTRO" = "buster" ]]; then
    sed -i "s~ buster main$~ buster main contrib non-free~" \
        /etc/apt/sources.list
    sed -i "s~ buster-updates main$~ buster-updates main contrib non-free~" \
        /etc/apt/sources.list
    sed -i "s~ buster/updates main$~ buster/updates main contrib non-free~" \
        /etc/apt/sources.list
fi

wget -T 10 -qO /tmp/google-chrome.gpg.key \
    https://dl.google.com/linux/linux_signing_key.pub
apt-key add /tmp/google-chrome.gpg.key
wget -T 10 -O /etc/apt/sources.list.d/google-chrome.list \
    $JIBRI_TMPL/etc/apt/sources.list.d/google-chrome.list

apt-get -y --allow-releaseinfo-change update
apt-get $APT_PROXY_OPTION -y install kmod alsa-utils
apt-get $APT_PROXY_OPTION -y install libnss3-tools unzip unclutter
apt-get $APT_PROXY_OPTION -y install va-driver-all vdpau-driver-all
apt-get $APT_PROXY_OPTION -y --install-recommends install ffmpeg
apt-get $APT_PROXY_OPTION -y --install-recommends install google-chrome-stable

CHROME_VER=$(dpkg -s google-chrome-stable | egrep "^Version" | \
    cut -d " " -f2 | cut -d. -f1)
CHROMEDRIVER_VER=$(curl -s \
    https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VER)
wget -T 10 -qO /tmp/chromedriver_linux64.zip \
    https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VER/chromedriver_linux64.zip
unzip -o /tmp/chromedriver_linux64.zip -d /usr/local/bin/
chmod 755 /usr/local/bin/chromedriver

apt-get $APT_PROXY_OPTION -y install x11vnc
apt-get $APT_PROXY_OPTION -y install jibri

apt-get -y purge upower
apt-get -y --purge autoremove

# jibri packages are ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-package-jibri" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# packages (extra, videosipgw)
# -----------------------------------------------------------------------------
out <<< "installing videosipgw packages..."

apt-get -y install kmod v4l2loopback-dkms
apt-get -y install build-essential
apt-get -y install libv4l-dev libsdl2-dev libavcodec-dev libavdevice-dev \
    libavfilter-dev libavformat-dev libavresample-dev libavutil-dev \
    libswresample-dev libswscale-dev libasound2-dev libopus-dev libvpx-dev

# videosipgw packages are ok
timeout 8 curl -s \
    "$CHECKMYPORT?proto=udp&port=60000&text=ok-package-videosipgw" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# backup
# -----------------------------------------------------------------------------
# jitsi-meet
cp $JITSI_MEET_CONFIG $JITSI_MEET_CONFIG.org

# coturn
cp /etc/turnserver.conf /etc/turnserver.conf.org

# prosody
cp /etc/prosody/prosody.cfg.lua /etc/prosody/prosody.cfg.lua.org
cp $PROSODY_CONFIG $PROSODY_CONFIG.org

# jicofo
cp /etc/jitsi/jicofo/config /etc/jitsi/jicofo/config.org
cp /etc/jitsi/jicofo/jicofo.conf /etc/jitsi/jicofo/jicofo.conf.org

# jvb
cp /etc/jitsi/videobridge/config /etc/jitsi/videobridge/config.org
cp /etc/jitsi/videobridge/jvb.conf /etc/jitsi/videobridge/jvb.conf.org
cp /etc/jitsi/videobridge/sip-communicator.properties \
    /etc/jitsi/videobridge/sip-communicator.properties.org

# nginx
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
cp $NGINX_CONFIG $NGINX_CONFIG.org

# jibri
cp /opt/jitsi/jibri/pjsua.sh /opt/jitsi/jibri/pjsua.sh.org
cp /opt/jitsi/jibri/finalize_sip.sh /opt/jitsi/jibri/finalize_sip.sh.org


# -----------------------------------------------------------------------------
# backup (extra)
# -----------------------------------------------------------------------------
cp /etc/modules /etc/modules.org
cp /etc/hosts /etc/hosts.org
cp /usr/share/jitsi-meet/body.html /usr/share/jitsi-meet/body.html.org


# -----------------------------------------------------------------------------
# configuration (extra, jibri)
# -----------------------------------------------------------------------------
out <<< "jibri related configuration..."

# snd_aloop
[[ -z "$(egrep '^snd_aloop' /etc/modules)" ]] && echo snd_aloop >>/etc/modules

# snd_aloop options (extra, videosipgw)
wget -T 10 -O /etc/modprobe.d/alsa-loopback.conf \
    $JIBRI_TMPL/etc/modprobe.d/alsa-loopback.conf

modprobe snd-aloop

# hosts
sed -i -E "s/(\s)$JITSI_HOST/\1/" /etc/hosts
sed -i -E "/^[0-9.]+\s*$/d" /etc/hosts
sed -i "/127.0.2.1\s/d" /etc/hosts
sed -i "$ a 127.0.2.1 $JITSI_HOST" /etc/hosts

# google chrome
mkdir -p /etc/opt/chrome/policies/managed
wget -T 10 -O /etc/opt/chrome/policies/managed/jibri_policies.json \
    $JIBRI_TMPL/etc/opt/chrome/policies/managed/jibri_policies.json


# -----------------------------------------------------------------------------
# configuration (extra, videosipgw)
# -----------------------------------------------------------------------------
out <<< "videosipgw related configuration..."

# v4l2loopback options
wget -T 10 -O /etc/modprobe.d/v4l2loopback.conf \
    $JIBRI_TMPL/etc/modprobe.d/v4l2loopback.conf

# v4l2loopback
[[ -z "$(egrep '^v4l2loopback' /etc/modules)" ]] && \
    echo v4l2loopback >>/etc/modules

modprobe v4l2loopback

# xorg DISPLAY :1
wget -T 10 -O /etc/systemd/system/sip-xorg.service \
    $JIBRI_TMPL/etc/systemd/system/sip-xorg.service

systemctl daemon-reload
systemctl enable sip-xorg.service
systemctl start sip-xorg.service


# -----------------------------------------------------------------------------
# certbot
# -----------------------------------------------------------------------------
out <<< "configuring Certbot..."

mkdir -p /etc/systemd/system/certbot.service.d
wget -T 10 -O /etc/systemd/system/certbot.service.d/override.conf \
    $JITSI_TMPL/etc/systemd/system/certbot.service.d/override.conf
systemctl daemon-reload

# certbot config is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-certbot" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# coturn
# -----------------------------------------------------------------------------
out <<< "configuring Coturn..."

cat >>/etc/turnserver.conf <<EOF

# the following lines added by eb-jitsi
listening-ip=$PUBLIC_IP
allowed-peer-ip=$PUBLIC_IP
no-udp
EOF

adduser turnserver ssl-cert
systemctl restart coturn.service

# coturn config is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-coturn" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# prosody
# -----------------------------------------------------------------------------
out <<< "configuring Prosody..."

mkdir -p /etc/systemd/system/prosody.service.d
wget -T 10 -O /etc/systemd/system/prosody.service.d/override.conf \
    $JITSI_TMPL/etc/systemd/system/prosody.service.d/override.conf
wget -T 10 -O /etc/prosody/conf.avail/network.cfg.lua \
    $JITSI_TMPL/etc/prosody/conf.avail/network.cfg.lua
ln -s ../conf.avail/network.cfg.lua /etc/prosody/conf.d/
sed -i "/rate *=.*kb.s/  s/[0-9]*kb/1024kb/" /etc/prosody/prosody.cfg.lua
sed -i "s/^-- \(https_ports = { };\)/\1/" $PROSODY_CONFIG
sed -i "/turns.*tcp/ s/host\s*=[^,]*/host = \"$TURN_HOST\"/" $PROSODY_CONFIG
sed -i "/turns.*tcp/ s/5349/443/" $PROSODY_CONFIG

# extra (token)
wget -T 10 -O /usr/share/jitsi-meet/prosody-plugins/mod_token_affiliation.lua \
    $PROSODY_PLUGINS/token_affiliation/mod_token_affiliation.lua

sed -i '/\s*app_secret=/a \
\    allow_empty_token = false' $PROSODY_CONFIG
sed -i '/^Component .conference\./,/admins/!b; /\s*"token_verification"/a \
\        "token_affiliation";' $PROSODY_CONFIG

# extra (jibri, videosipgw)
wget -T 10 -O /etc/prosody/conf.avail/sip.$JITSI_HOST.cfg.lua \
    $JITSI_TMPL/etc/prosody/conf.avail/sip.cfg.lua
sed -i "s/___JITSI_HOST___/$JITSI_HOST/" \
    /etc/prosody/conf.avail/sip.$JITSI_HOST.cfg.lua
ln -s ../conf.avail/sip.$JITSI_HOST.cfg.lua /etc/prosody/conf.d/

sed -i -r "0,/^\s*admins/ s/(^\s*admins).*/\1 = { \
\"focus@auth.$JITSI_HOST\", \
\"sip@sip.$JITSI_HOST\" }/" \
    $PROSODY_CONFIG

# prosody restart
systemctl daemon-reload
systemctl restart prosody.service

# prosody accounts (extra, jibri)
PASSWD1=$(openssl rand -hex 20)
PASSWD2=$(openssl rand -hex 20)

prosodyctl unregister jibri auth.$JITSI_HOST || true
prosodyctl register jibri auth.$JITSI_HOST $PASSWD1
prosodyctl unregister sip sip.$JITSI_HOST || true
prosodyctl register sip sip.$JITSI_HOST $PASSWD2

# prosody config is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-prosody" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jicofo
# -----------------------------------------------------------------------------
out <<< "configuring Jicofo..."

hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.conference.enable-auto-owner true

sed -i '/^JICOFO_AUTH_PASSWORD=/a \
\
# set the maximum memory for the jicofo daemon\
JICOFO_MAX_MEMORY=3072m' \
    /etc/jitsi/jicofo/config

# extra (token)
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.conference.enable-auto-owner false

# extra (videosipgw)
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.jibri-sip.brewery-jid \
    "\"SipBrewery@internal.auth.$JITSI_HOST\""

# jicofo restart
systemctl restart jicofo.service

# jicofo config is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-jicofo" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jitsi-meet (extra, token)
# -----------------------------------------------------------------------------
sed -i -r 's~//\s*(disableProfile).*~\1: true,~' $JITSI_MEET_CONFIG
sed -i -r 's~//\s*(enableFeaturesBasedOnToken).*~\1: true,~' $JITSI_MEET_CONFIG

# jitsi-meet config is ok
timeout 8 curl -s \
    "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-jitsi-meet-token" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jitsi-meet (extra, videosipgw)
# -----------------------------------------------------------------------------
wget -T 10 -O /usr/share/jitsi-meet/static/sip-people-sample.json \
    $JITSI_TMPL/usr/share/jitsi-meet/static/sip-people-sample.json

sed -i "/^\s*enableFeaturesBasedOnToken/a \
\\
\n\
\    peopleSearchQueryTypes: ['conferenceRooms'],\n\
\    peopleSearchUrl: 'https://$JITSI_HOST/static/sip-people-sample.json'," \
    $JITSI_MEET_CONFIG

# jitsi-meet config is ok
timeout 8 curl -s \
    "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-jitsi-meet-token" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# nginx
# -----------------------------------------------------------------------------
out <<< "configuring Nginx..."

mkdir -p /etc/systemd/system/nginx.service.d
wget -T 10 -O /etc/systemd/system/nginx.service.d/override.conf \
    $JITSI_TMPL/etc/systemd/system/nginx.service.d/override.conf

sed -i "/worker_connections/ s/\\S*;/8192;/" \
    /etc/nginx/nginx.conf

mkdir -p /usr/local/share/nginx/modules-available
wget -T 10 -O /usr/local/share/nginx/modules-available/jitsi-meet.conf \
    $JITSI_TMPL/usr/local/share/nginx/modules-available/jitsi-meet.conf
sed -i "s/___LOCAL_IP___/$PUBLIC_IP/" \
    /usr/local/share/nginx/modules-available/jitsi-meet.conf
sed -i "s/___TURN_HOST___/$TURN_HOST/" \
    /usr/local/share/nginx/modules-available/jitsi-meet.conf

wget -T 10 -O /etc/nginx/sites-available/$JITSI_HOST.conf \
    $JITSI_TMPL/etc/nginx/sites-available/jms.conf
sed -i "s/___JITSI_HOST___/$JITSI_HOST/" $NGINX_CONFIG
sed -i "s/___TURN_HOST___/$TURN_HOST/" $NGINX_CONFIG

ln -s /usr/local/share/nginx/modules-available/jitsi-meet.conf \
    /etc/nginx/modules-enabled/99-jitsi-meet-custom.conf
rm /etc/nginx/sites-enabled/default
rm -rf /var/www/html
ln -s /usr/share/jitsi-meet /var/www/html

systemctl daemon-reload
systemctl stop nginx.service
systemctl start nginx.service

# nginx config is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-nginx" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jvb
# -----------------------------------------------------------------------------
out <<< "configuring JVB..."

# default memory limit
sed -i '/^JVB_SECRET=/a \
\
# set the maximum memory for the JVB daemon\
VIDEOBRIDGE_MAX_MEMORY=3072m' \
    /etc/jitsi/videobridge/config

# colibri
hocon -f /etc/jitsi/videobridge/jvb.conf \
    set videobridge.apis.rest.enabled true
hocon -f /etc/jitsi/videobridge/jvb.conf \
    set videobridge.ice.udp.port 10000

# NAT harvester
[[ "$EXTERNAL_IP" = "$PUBLIC_IP" ]] && COMMENT="#"
cat >>/etc/jitsi/videobridge/sip-communicator.properties <<EOF
${COMMENT}org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$PUBLIC_IP
${COMMENT}org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$EXTERNAL_IP
EOF

systemctl restart jitsi-videobridge2.service

# jvb config is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-jvb" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# lets encrypt
# -----------------------------------------------------------------------------
out <<< "setting Let's Encrypt certificates..."

certbot certonly --dry-run --non-interactive -m info@$JITSI_HOST --agree-tos \
    --duplicate --webroot -w /var/www/html -d $JITSI_HOST,$TURN_HOST || true
sleep 3
certbot certonly --non-interactive -m info@$JITSI_HOST --agree-tos \
    --duplicate --webroot -w /var/www/html -d $JITSI_HOST,$TURN_HOST

rm -f /etc/jitsi/meet/$JITSI_HOST.crt
rm -f /etc/jitsi/meet/$JITSI_HOST.key
ln -s /etc/letsencrypt/live/$JITSI_HOST/fullchain.pem \
    /etc/jitsi/meet/$JITSI_HOST.crt
ln -s /etc/letsencrypt/live/$JITSI_HOST/privkey.pem \
    /etc/jitsi/meet/$JITSI_HOST.key

out <<< "restarting Certbot..."
systemctl restart certbot.service

out <<< "restarting Coturn..."
systemctl restart coturn.service

out <<< "restarting Nginx..."
systemctl restart nginx.service

# tls is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-tls" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# jibri related (extra)
# -----------------------------------------------------------------------------
# icewm
mkdir -p /home/jibri/.icewm
wget -T 10 -O /home/jibri/.icewm/startup $JIBRI_TMPL/home/jibri/.icewm/startup
chmod 755 /home/jibri/.icewm/startup

# jibri
chsh -s /bin/bash jibri
usermod -aG adm,audio,video,plugdev jibri

wget -T 10 -O /etc/jitsi/jibri/jibri.conf \
    $JIBRI_TMPL/etc/jitsi/jibri/jibri.videosipgw.conf
sed -i "s/___JITSI_HOST___/$JITSI_HOST/" /etc/jitsi/jibri/jibri.conf
sed -i "s/___PASSWD1___/$PASSWD1/" /etc/jitsi/jibri/jibri.conf
sed -i "s/___PASSWD2___/$PASSWD2/" /etc/jitsi/jibri/jibri.conf

wget -T 10 -O /usr/local/bin/ffmpeg $JIBRI_TMPL/usr/local/bin/ffmpeg
chmod 755 /usr/local/bin/ffmpeg

systemctl daemon-reload
systemctl enable jibri.service
systemctl start jibri.service

# jibri, vnc
mkdir -p /home/jibri/.vnc
x11vnc -storepasswd jibri /home/jibri/.vnc/passwd
chown jibri:jibri /home/jibri/.vnc -R

# jibri, Xdefaults
wget -T 10 -O /home/jibri/.Xdefaults $JIBRI_TMPL/home/jibri/.Xdefaults
chown jibri:jibri /home/jibri/.Xdefaults

# jibri configuration is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-jibri" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# SIP dialing plan (extra)
# -----------------------------------------------------------------------------
# deno
LATEST=$(curl -sSf https://github.com/denoland/deno/releases | \
    grep -o "/denoland/deno/releases/download/.*/deno-.*linux.*\.zip" | \
    head -n1)

cd /tmp
wget -T 30 -O deno.zip https://github.com/$LATEST
unzip -o deno.zip
cp /tmp/deno /usr/local/bin/

# sip-dial-plan
su -l jibri <<EOS
set -e

git clone https://github.com/jitsi-contrib/sip-dial-plan.git
EOS

sed -i "/TOKEN_SECRET/ s/\".*\"/\"$APP_SECRET\"/" \
    /home/jibri/sip-dial-plan/config.ts



# -----------------------------------------------------------------------------
# PJSUA related (extra)
# -----------------------------------------------------------------------------
# build
mkdir /home/jibri/src
chown jibri:jibri /home/jibri/src

su -l jibri <<EOS
set -e

cd ~/src

git clone -b $PJPROJECT_BRANCH $PJPROJECT_REPO
cd pjproject

./configure
make dep
make
EOS

cp /home/jibri/src/pjproject/pjsip-apps/bin/pjsua-x86_64-unknown-linux-gnu \
    /usr/local/bin/pjsua
chmod 755 /usr/local/bin/pjsua

# pjsua scripts
wget -T 10 -O /opt/jitsi/jibri/pjsua.sh $JIBRI_TMPL/opt/jitsi/jibri/pjsua.sh
wget -T 10 -O /opt/jitsi/jibri/finalize_sip.sh \
    $JIBRI_TMPL/opt/jitsi/jibri/finalize_sip.sh

# pjsua configuration is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-pjsua" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# completed (extra)
# -----------------------------------------------------------------------------
out <<EOF
Your App ID: $APP_ID
Your App Secret: $APP_SECRET
EOF

timeout 8 curl -s \
    "$CHECKMYPORT?proto=udp&port=60000&text=ok-jitsi-videosipgw" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# completed
# -----------------------------------------------------------------------------
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-completed" \
    >/dev/null || true

END_TIME=$(date +%s)
DURATION=$(date -u -d "0 $END_TIME seconds - $START_TIME seconds" +"%H:%M:%S")
COMPLETED=true
