#!/bin/bash

# -----------------------------------------------------------------------------
# extra for jitsi-token-installer
# -----------------------------------------------------------------------------
JICOFO_CONFIG=/etc/jitsi/jicofo/jicofo.conf
PROSODY_CONFIG=/etc/prosody/conf.avail/$JITSI_HOST.cfg.lua
JITSI_MEET_CONFIG=/etc/jitsi/meet/$JITSI_HOST-config.js
APP_ID="jitsi-$RANDOM"
APP_SECRET="$(openssl rand -hex 20)"


# -----------------------------------------------------------------------------
# packages
# -----------------------------------------------------------------------------
out <<< "installing token packages..."

debconf-set-selections <<< \
    "jitsi-meet-tokens jitsi-meet-tokens/appid string $APP_ID"
debconf-set-selections <<< \
    "jitsi-meet-tokens jitsi-meet-tokens/appsecret password $APP_SECRET"
apt-get -y install jitsi-meet-tokens

# token packages are ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-package-token" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# configuration
# -----------------------------------------------------------------------------
out <<< "token configuration..."

# prosody
sed -i '/\s*app_secret=/a \
\    allow_empty_token = false' $PROSODY_CONFIG
sed -i '/^Component .conference\./,/admins/!b; /\s*"token_verification"/a \
\        "token_affiliation";' $PROSODY_CONFIG

systemctl restart prosody.service

# jicofo
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.conference.enable-auto-owner false
systemctl restart jicofo.service
systemctl restart jitsi-videobridge2.service

# jitsi-meet config
sed -i -r 's~//\s*(disableProfile).*~\1: true,~' $JITSI_MEET_CONFIG
sed -i -r 's~//\s*(enableFeaturesBasedOnToken).*~\1: true,~' $JITSI_MEET_CONFIG

# token configuration is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-token" \
    >/dev/null || true


# -----------------------------------------------------------------------------
# completed
# -----------------------------------------------------------------------------
out <<EOF
Your App ID: $APP_ID
Your App Secret: $APP_SECRET
EOF

# token completed
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-token" \
    >/dev/null || true
