#!/bin/bash

chromium https://___JITSI_HOST___ &
sleep 30
pkill --oldest --signal TERM chrome
pkill --oldest --signal TERM chromium

#x11vnc -display :0 -nolookup -once -loop -usepw -shared -noxdamage -nodpms &
