#!/bin/bash

# -----------------------------------------------------------------------------
# extra for jitsi-secure-installer
# -----------------------------------------------------------------------------
JICOFO_CONFIG=/etc/jitsi/jicofo/jicofo.conf
PROSODY_CONFIG=/etc/prosody/conf.avail/$JITSI_HOST.cfg.lua
JITSI_MEET_CONFIG=/etc/jitsi/meet/$JITSI_HOST-config.js

# -----------------------------------------------------------------------------
# configuration
# -----------------------------------------------------------------------------
out <<< "secure-domain configuration..."

# prosody
wget -T 30 -O /etc/prosody/conf.avail/guest.$JITSI_HOST.cfg.lua \
    $JITSI_TMPL/etc/prosody/conf.avail/guest.cfg.lua
sed -i "s/___JITSI_HOST___/$JITSI_HOST/" \
    /etc/prosody/conf.avail/guest.$JITSI_HOST.cfg.lua
ln -s ../conf.avail/guest.$JITSI_HOST.cfg.lua /etc/prosody/conf.d/

sed -i '/^\s*authentication/ s/jitsi-anonymous/internal_hashed/' $PROSODY_CONFIG

systemctl restart prosody.service

# jicofo
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.conference.enable-auto-owner false
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.authentication.enabled true
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.authentication.type "XMPP"
hocon -f /etc/jitsi/jicofo/jicofo.conf \
    set jicofo.authentication.login-url "$JITSI_HOST"
systemctl restart jicofo.service
systemctl restart jitsi-videobridge2.service

# jitsi-meet config
sed -i -r "/\s*domain:/a \
\        anonymousdomain: 'guest.$JITSI_HOST'," \
    $JITSI_MEET_CONFIG

# secure-domain configuration is ok
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-conf-secure" \
    >/dev/null || true

# -----------------------------------------------------------------------------
# completed
# -----------------------------------------------------------------------------
out <<EOF
DON'T FORGET TO CREATE ADMIN USERS:

prosodyctl register <USERNAME> $JITSI_HOST <PASSWORD>
EOF

# secure-domain completed
timeout 8 curl -s "$CHECKMYPORT?proto=udp&port=60000&text=ok-secure" \
    >/dev/null || true
